"use client";
import { useCallback, useEffect, useState } from "react";
import { Calendar03Icon, ArrowLeft01Icon, ArrowRight01Icon, Add01Icon } from "hugeicons-react";

type Event = {id:string;title:string;description:string|null;scheduledAt:string;durationMinutes:number;eventType:string;isLive:boolean;endedAt:string|null;liveUrl:string|null;isRegistered:boolean;rsvpCount:number};
const dayKey=(date:Date)=>`${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`;
export default function NetworkEvents({slug, isOwner, onEventsChange}:{slug:string;isOwner:boolean;onEventsChange?:(events:Event[])=>void}) {
  const [events,setEvents]=useState<Event[]>([]),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
  const [selected,setSelected]=useState<string|null>(null),[showForm,setShowForm]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=useCallback(async(signal?:AbortSignal)=>{
    try{const r=await fetch(`/api/pro-networks/${slug}/events`,{signal});if(!r.ok)throw Error("Could not load events.");const data=await r.json();if(signal?.aborted)return;setEvents(data.events);onEventsChange?.(data.events);setError("");}
    catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:"Could not load events.");}finally{if(!signal?.aborted)setLoading(false);}
  },[slug,onEventsChange]);
  useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
  async function create(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError("");
    try{const r=await fetch(`/api/pro-networks/${slug}/events`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:form.get("title"),description:form.get("description"),eventType:form.get("eventType"),scheduledAt:new Date(String(form.get("scheduledAt"))).toISOString(),durationMinutes:Number(form.get("duration")),liveUrl:form.get("url")||null,isMembersOnly:true})});const data=await r.json();if(!r.ok)throw Error(data.error);const date=new Date(data.event.scheduledAt);setMonth(new Date(date.getFullYear(),date.getMonth(),1));setSelected(dayKey(date));setShowForm(false);await load();}
    catch(e){setError(e instanceof Error?e.message:"Could not create event.");}finally{setBusy(false);}
  }
  async function action(id:string,kind:"rsvp"|"room"){
    setBusy(true);setError("");try{const r=await fetch(`/api/pro-networks/${slug}/events/${id}/${kind}`,{method:"POST"});const data=await r.json();if(!r.ok)throw Error(data.error);if(data.url)window.location.assign(data.url);else await load();}catch(e){setError(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}
  }
  function download(event:Event){
    const escape=(s:string)=>s.replace(/\\/g,"\\\\").replace(/\r?\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;");
    const time=(d:Date)=>d.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const start=new Date(event.scheduledAt);
    const lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//TaxCompPro//Network Events//EN","BEGIN:VEVENT",`UID:${event.id}@taxcomppro.com`,`DTSTAMP:${time(new Date())}`,`DTSTART:${time(start)}`,`DTEND:${time(new Date(start.getTime()+event.durationMinutes*60000))}`,`SUMMARY:${escape(event.title)}`,`DESCRIPTION:${escape(event.description||"")}`,`URL:${window.location.origin}/pro-networks/${slug}`,"END:VEVENT","END:VCALENDAR"];
    const url=URL.createObjectURL(new Blob([lines.join("\r\n")],{type:"text/calendar;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="network-event.ics";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
  const visible=events.filter(e=>{const d=new Date(e.scheduledAt);return d.getMonth()===month.getMonth()&&d.getFullYear()===month.getFullYear()&&(!selected||dayKey(d)===selected);});
  return <section className="pn-settings-card pn-events"><div className="pn-settings-heading"><div><h3><Calendar03Icon size={24}/>Network events</h3><p>Meet, learn and connect. Times are shown in your local time zone.</p></div>{isOwner&&<button className="pn-button pn-primary" onClick={()=>setShowForm(!showForm)}><Add01Icon size={18}/>{showForm?"Close form":"Create event"}</button>}</div>
    {showForm&&<form onSubmit={create} className="pn-event-form"><label>Event title<input name="title" required maxLength={180}/></label><label>Description<textarea name="description" rows={3} maxLength={5000}/></label><div className="pn-brand-grid"><label>Event type<select name="eventType">{["PRO_TALK","LIVE_CLASS","WORKSHOP","WEBINAR","QA_SESSION"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label><label>Date and time<input name="scheduledAt" type="datetime-local" required/></label><label>Duration (minutes)<input name="duration" type="number" min={5} max={1440} defaultValue={60} required/></label><label>External meeting link (optional)<input name="url" type="url" placeholder="https://…"/></label></div><p>Members only. Leave the link blank to host a live Pro Talk inside your Network.</p><button className="pn-button pn-primary" disabled={busy}>{busy?"Saving…":"Schedule event"}</button></form>}
    <div className="pn-calendar-toolbar"><button className="pn-icon-button" aria-label="Previous month" onClick={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()-1,1));setSelected(null);}}><ArrowLeft01Icon size={20}/></button><h4>{month.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</h4><button className="pn-icon-button" aria-label="Next month" onClick={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()+1,1));setSelected(null);}}><ArrowRight01Icon size={20}/></button><button className="pn-button pn-secondary" onClick={()=>{const today=new Date();setMonth(new Date(today.getFullYear(),today.getMonth(),1));setSelected(null);}}>Today</button></div>
    <div className="pn-calendar" aria-label="Events calendar">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><strong key={d}>{d}</strong>)}{Array.from({length:month.getDay()},(_,i)=><span key={`blank${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=new Date(month.getFullYear(),month.getMonth(),i+1),key=dayKey(date),count=events.filter(e=>dayKey(new Date(e.scheduledAt))===key).length;return <button key={key} onClick={()=>setSelected(selected===key?null:key)} aria-pressed={selected===key} aria-current={key===dayKey(new Date())?"date":undefined} aria-label={`${date.toLocaleDateString()}, ${count} events`}><span>{i+1}</span>{count>0&&<small>{count}<span className="pn-calendar-word"> event{count!==1?"s":""}</span></small>}</button>;})}</div>
    {selected&&<button className="pn-button pn-secondary" onClick={()=>setSelected(null)}>Show whole month</button>}
    {error&&<p role="alert">{error} <button onClick={()=>void load()}>Retry</button></p>}
    {loading?<p role="status">Loading events…</p>:visible.length===0?<div className="pn-event-empty"><Calendar03Icon size={32}/><h4>No events {selected?"on this day":"this month"}</h4><p>{isOwner?"Create an event to bring your members together.":"Scheduled events will appear here."}</p></div>:visible.map(event=><article key={event.id} className="pn-event-item"><div><small>{new Date(event.scheduledAt).toLocaleString()} · {event.durationMinutes} min</small><h4>{event.title}</h4><p>{event.description}</p><small>{event.rsvpCount} registered{event.endedAt?" · Ended":event.isLive?" · Live now":""}</small></div><div className="pn-event-actions"><button className="pn-button pn-secondary" onClick={()=>download(event)}>Add to calendar</button>{!event.endedAt&&<><button className="pn-button pn-secondary" disabled={busy} onClick={()=>void action(event.id,"rsvp")}>{event.isRegistered?"Cancel RSVP":"RSVP"}</button>{(isOwner||event.isLive||event.liveUrl)&&<button className="pn-button pn-primary" disabled={busy} onClick={()=>void action(event.id,"room")}>{event.isLive||event.liveUrl?"Join event":"Start event"}</button>}</>}</div></article>)}
  </section>;
}
