import Image from "next/image";
import { TOOLKITS, BUNDLES, type Toolkit, type Bundle } from "@/lib/toolkits";
import { ArrowRight01Icon, Shield01Icon, StarIcon, FlashIcon, Award01Icon, Clock01Icon, UserGroupIcon, LockIcon, BookOpen01Icon, Tick02Icon, Layers01Icon } from "hugeicons-react";
import "@/components/courses/courses-directory.css";
import "@/components/courses/toolkits-directory.css";

function ToolkitCard({ tk }: { tk: Toolkit }) {
  return <article className="cd-card"><div className="cd-card-core"><a className="cd-card-image tk-art" href={tk.externalUrl} target="_blank" rel="noopener noreferrer" aria-label={`Access ${tk.name}`}><Image src={tk.badgeImage} alt={tk.name} fill unoptimized sizes="(max-width:700px) 100vw, 420px" /></a><div className="cd-card-body"><span className="cd-category">{tk.category}</span><h3>{tk.name}</h3><p className="cd-description">{tk.description}</p><a className="cd-card-action" href={tk.externalUrl} target="_blank" rel="noopener noreferrer">ACCESS TOOLKIT<span><ArrowRight01Icon size={18}/></span></a></div></div></article>;
}
function BundleCard({ bundle }: { bundle: Bundle }) {
  const plus=bundle.id==="ultimate-bundle-plus";
  return <article className="tk-bundle">{bundle.badgeImage && <div className="tk-bundle-cover"><Image src={bundle.badgeImage} alt={bundle.name} fill unoptimized sizes="(max-width:1000px) 100vw, 650px" /></div>}<span className="tk-badge"><Award01Icon size={16}/>{bundle.badge}</span>{plus && <p className="cd-category tk-plus">All Toolkits + All Video Masterclasses</p>}<div className="tk-bundle-heading"><div><h3>{bundle.name}</h3><p>{bundle.description}</p></div></div><ul>{bundle.features.map(feature=><li key={feature}><Tick02Icon size={16}/><span>{feature}</span></li>)}</ul><a className="cd-card-action" href={bundle.externalUrl} target="_blank" rel="noopener noreferrer">{plus ? "ACCESS ULTIMATE PLUS BUNDLE" : "ACCESS ULTIMATE BUNDLE"}<span><ArrowRight01Icon size={18}/></span></a></article>;
}
const benefits = [
  { Icon: Shield01Icon, title: "IRS Penalty Protection", description: "Every kit includes penalty defense resources, due diligence forms, and compliance documentation that protect you in an audit." },
  { Icon: Award01Icon, title: "Revenue Growth Strategies", description: "Proven pricing models, marketing blueprints, and referral systems that directly increase your bottom line." },
  { Icon: Layers01Icon, title: "Done-For-You Templates", description: "Response letters, audit prep systems, client intake forms, and office policy documents — all ready to use." },
  { Icon: BookOpen01Icon, title: "Step-by-Step Playbooks", description: "No fluff. Each toolkit is a step-by-step operational guide built for real-world tax practice environments." },
  { Icon: UserGroupIcon, title: "2 Months Free Marketplace Membership Plus", description: "Every toolkit purchase includes 2 months of VIP community access — mentorship, networking, and exclusive resources." },
  { Icon: LockIcon, title: "Instant Secure Access", description: "Immediately access your downloads after purchase. All files are hosted securely and updated regularly." },
];
export default function ToolkitsPage() {
  return <div className="cd-page tk-page"><div className="cd-container"><section className="cd-hero"><div className="cd-hero-copy"><span className="cd-eyebrow"><Layers01Icon size={18}/>Premium Digital Resources · Instant Access</span><h1>The Toolkits <span>Top Tax Pros</span> Use to Dominate.</h1><p>Premium digital resources for Tax Professionals — each kit includes exclusive tools, templates, courses, and Free Marketplace Membership Plus.</p><div className="tk-hero-actions"><a className="tk-primary" href="#toolkits">Browse Toolkits <ArrowRight01Icon size={17}/></a><a className="tk-secondary" href="#bundles">View Practice Bundles</a></div><div className="cd-benefits">{[{ Icon: Shield01Icon,label:"IRS-Compliant Standards" },{ Icon: FlashIcon,label:"Instant Access" },{ Icon: Award01Icon,label:"Proven Blueprints" },{ Icon: Clock01Icon,label:"2 Months Free Marketplace Membership Plus" }].map(({Icon,label})=><span key={label}><Icon size={18}/>{label}</span>)}</div></div><div className="cd-hero-art"><Image src="/irs-toolkit-audit-review-hero.webp" alt="IRS Toolkit Audit Review" width={720} height={720} priority unoptimized/><span><StarIcon size={14}/>Professional Grade</span></div></section>
  <div className="cd-stats">{[{num:"6",label:"Professional Toolkits"},{num:"100%",label:"IRS-Compliant Workpapers"},{num:"10+",label:"Templates per Toolkit"},{num:"2 mo",label:"Free Marketplace Membership Plus"}].map(s=><div key={s.label}><strong>{s.num}</strong><span>{s.label}</span></div>)}</div>
  <section id="toolkits" className="cd-catalog"><header className="cd-catalog-heading"><span className="cd-eyebrow"><StarIcon size={15}/>Practice Growth &amp; Defense Systems</span><h2>Individual Toolkits</h2><p>Choose the exact toolkit built for your firm&apos;s launch, due diligence, compliance, and audit defense.</p><div className="cd-offer"><Award01Icon size={20}/><p>Receive 2 Months FREE Marketplace Membership Plus with the purchase of ANY Toolkit or Course Bundle.</p></div></header><div className="cd-grid">{TOOLKITS.map(tk=><ToolkitCard key={tk.id} tk={tk}/>)}</div></section>
  {!!BUNDLES.length && <section id="bundles" className="cd-catalog"><header id="bundle" className="cd-catalog-heading"><span className="cd-eyebrow"><Layers01Icon size={16}/>Practice Defense Suites</span><h2>Practice Defense Bundles</h2><p>Get complete practice coverage. Choose between our comprehensive Toolkit Suite or the Flagship Suite with complete Video Masterclasses &amp; Staff Certifications.</p></header><div className="tk-bundles">{BUNDLES.map(bundle=><BundleCard key={bundle.id} bundle={bundle}/>)}</div></section>}
  <section className="tk-why"><header className="cd-catalog-heading"><span className="cd-eyebrow">Why Tax Compliance Pro Toolkits</span><h2>Built by practitioners. Designed to protect your practice.</h2><p>Every toolkit is built around one goal: helping tax professionals reduce risk, grow revenue, and run a tighter, more compliant operation.</p></header><div className="tk-benefit-grid">{benefits.map(({Icon,title,description})=><article key={title}><span><Icon size={23}/></span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
  <section className="tk-final"><span className="cd-eyebrow"><FlashIcon size={16}/>Start protecting your practice today</span><h2>The IRS won&apos;t wait. Neither should you.</h2><p>Get the toolkit that matches your biggest challenge and start building a protected, profitable operation today.</p><a href="#toolkits" className="tk-primary">Shop Toolkits <ArrowRight01Icon size={17}/></a></section>
  </div></div>;
}
